#!/bin/busybox sh

export PATH=/bin:/sbin:/usr/bin:/usr/sbin

/bin/busybox mount -t devtmpfs devtmpfs /dev
/bin/busybox mount -t proc proc /proc
/bin/busybox mount -t sysfs sysfs /sys

echo "OJLinux: Initramfs started"
echo "OJLinux: Waiting for root filesystem setup"

exec /bin/busybox sh
